### ISSUE TITLE
[Bug] Confusing Repo Naming

### ISSUE THREAD

**Issue by Sabyasachi-Seal** [skills/review-pull-requests#19]
**Describe the bug**
Confusion while making the new repo.

**To Reproduce**
1. Go to ['https://github.com/Sabyasachi-Seal/review-pull-requests'](https://github.com/Sabyasachi-Seal/review-pull-requests)
2. Scroll down to "How to start this couse"
3. See error on the picture. the picture says "introduction-to-github" but it should be something else as then Introduction to Github training repo is already having that link. 

**Expected behavior**
The screenshot should have something like the following. This will make the process much more self explainable.
![image](https://user-images.githubusercontent.com/36451386/213235362-e15249f6-2e99-4586-a967-0889675bee35.png)

**Screenshots**
![image](https://user-images.githubusercontent.com/36451386/213235467-69ddf71e-f9af-482b-8418-5cedafe792de.png)

**Comment by heiskr** [comment]
We've updated the courses to make the image more generally applicable.
