### ISSUE TITLE
https://github.com/cbhavya09/ci-workflow   - can you check here what needs to be done.

### ISSUE THREAD

**Issue by badges7** [skills/review-pull-requests#40]
https://github.com/cbhavya09/ci-workflow   - can you check here what needs to be done.

_Originally posted by @cbhavya09 in https://github.com/skills/.github/discussions/247#discussioncomment-6107305_

**Comment by hectorsector** [comment]
👋 @badges7 please use https://github.com/orgs/skills/discussions for support on the course!
