### ISSUE TITLE
[Bug] Repeating Readme files causing endless loop for a student

### ISSUE THREAD

**Issue by bhbooton** [skills/review-pull-requests#57]
### Summary

ReadMe files on this exercise repeat themselves creating an endless loop for the student.
### How to reproduce

1. Go to ['...'](https://learn.microsoft.com/en-us/training/modules/manage-changes-pull-requests-github/3-review-pull-requests)

2. Click on 'Start Exercise on GitHub'
3. Click on 'Read Me'
4. Create 'Create Repository'
5. follow instructions
6. Click on "read me' as instructions says
7. exact same instructions

Please include screenshots.
![GitHubError](https://github.com/skills/review-pull-requests/assets/36721412/f12ba5d3-1a4a-4368-aac5-da0eb308e958)

### Additional context
I did find what looks like what was intended in the folder > .github > steps

**Comment by FejanG** [comment]
comment

**Comment by AnnaNeuCurrent** [comment]
@bhbooton

**Comment by AnnaNeuCurrent** [comment]
> ### Summary
> ReadMe files on this exercise repeat themselves creating an endless loop for the student.
> 
> ### How to reproduce
> 1. Go to ['...'](https://learn.microsoft.com/en-us/training/modules/manage-changes-pull-requests-github/3-review-pull-requests)
> 2. Click on 'Start Exercise on GitHub'
> 3. Click on 'Read Me'
> 4. Create 'Create Repository'
> 5. follow instructions
> 6. Click on "read me' as instructions says
> 7. exact same instructions
> 
> Please include screenshots. ![GitHubError](https://private-user-images.githubusercontent.com/36721412/295374458-f12ba5d3-1a4a-4368-aac5-da0eb308e958.JPG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc2NDYxNDQsIm5iZiI6MTcwNzY0NTg0NCwicGF0aCI6Ii8zNjcyMTQxMi8yOTUzNzQ0NTgtZjEyYmE1ZDMtMWE0YS00MzY4LWFhYzUtZGEwZWIzMDhlOTU4LkpQRz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjExVDEwMDQwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThhYWVhMTZmMzY4OTZhNTU2ZmExZWYzZGVkNTA2MDgxM2IwNzJjMDM3NjAzN2M0NWJiZDNjMzYwMWZjYzlmMTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.RZXa89sI4cDOTCIbJOirF2vmNXR11SYQiNCogzjsW5E)
> 
> ### Additional context
> I did find what looks like what was intended in the folder > .github > steps
> 
> Add any other context about the problem here.

**Comment by engvuchen** [comment]
I have the same problem

**Comment by hectorsector** [comment]
Thanks for the report, @bhbooton. After a few seconds, the course provides the right content as indicated in the instructions:

> After your new repository is created, wait about 20 seconds, then refresh the page. Follow the step-by-step instructions in the new repository's README.

I'll mark this as closed but please drop back in if I misunderstood.
