### ISSUE TITLE
Prerequisites or assumptions suggestion

### ISSUE THREAD

**Issue by dnielsen2022** [skills/review-pull-requests#6]
**Is your feature request related to a problem? Please describe.**
Just a suggestion to add the assumptions or prerequisites before Step 1

**Describe the solution you'd like**
This module assumes you completed X or have existing knowledge of pull requests and creating them...etc.

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by heiskr** [comment]
We are open to pull requests if you have suggestions :)

**Comment by D-HackCoder** [comment]
How can I get that gif or badge??? I have completed all tasks.

**Comment by heiskr** [comment]
This course mentions:

> Prerequisites: We assume you are familiar with creating branches, commits, and pull requests—you can learn this in our [Introduction to GitHub](https://github.com/skills/introduction-to-github) course.

Let us know if that needs clarification, thank you for the issue!
